service: pylambda-basic

custom:
  env: ${file(./env/${opt:stage,'local'}.json)}
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  memorySize: 512

functions:
  hello:
    handler: index.fn_start
    events:
      - http:
          path: index/hello
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-prune-plugin
  #- serverless-layers
